"""
Read a resolved CIQ template Excel file and return structured data.

Design principle (after the effective-tax-rate incident):

    *** Route by the FORMULA, not the row-map. ***

The row-map sheet is a hint from the generator. It can be wrong (and was,
for the effective_tax_rate_ciq row, whose period string was "IQ_FY" — a
value that matched none of the reader's old routing patterns, so the
fetched value was silently dropped). Trusting it makes the reader brittle.

Instead: for every data row, parse the actual CIQ() call in column C and
extract the period from the 3rd positional argument. Route based on that.
The row-map is still consulted for (row-number, variable-name) mapping,
but its `period` column is treated as a fallback hint only.

This also makes the reader forgiving of xlsx files that were hand-edited
or generated by older versions of the template generator.

Returns:
    {
        "ticker": str,
        "annual": {fy_offset: {variable: value}},
        "quarterly": {fq_offset: {variable: value}},
        "current": {variable: value},
        "period_dates": {variable: value},
        "geo_segments": [{"rank": int, "name": str, "revenue": float, "pct": float}, ...],
    }
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timedelta
from pathlib import Path

import openpyxl

logger = logging.getLogger(__name__)


# ── CIQ formula parser ────────────────────────────────────────────────────
#
# Accepts the three forms we see in the wild:
#
#   =CIQ($B$1,"IQ_TOTAL_REV","IQ_FY-0")
#   =_xll.ciqfunctions.udf.CIQ($B$1,"IQ_CLOSEPRICE")
#   =ABS(CIQ($B$1,"IQ_CAPEX","IQ_FY-0"))
#   =CIQ($B$1,"IQ_EFFECT_TAX_RATE","IQ_FY")/100
#   =CIQ($B$1,"IQ_MARKETCAP","","REPORTED")
#   =CIQ($B$1,"IQ_GEO_SEG_NAME_ABS","IQ_FY",,,,,,1)
#
# Returns dict with mnemonic / period / ccy_scope / rank, or None.

_CIQ_CALL_RE = re.compile(
    r"(?:_xll\.ciqfunctions\.udf\.)?CIQ\s*\(",
    re.IGNORECASE,
)


def parse_ciq_formula(formula) -> dict | None:
    """Extract (mnemonic, period, ccy_scope, rank) from a CIQ formula string.

    Returns None if the cell doesn't contain a CIQ call we can parse.
    Missing positional args resolve to None. Empty-string args also resolve
    to None (CIQ treats "" and absent as equivalent for the period slot).
    """
    if not isinstance(formula, str):
        return None
    f = formula.lstrip("=").strip()
    m = _CIQ_CALL_RE.search(f)
    if not m:
        return None
    start = m.end()
    # Find the matching closing paren for this CIQ( call
    depth = 1
    end = None
    in_str = False
    i = start
    while i < len(f):
        ch = f[i]
        if ch == '"' and (i == 0 or f[i - 1] != "\\"):
            in_str = not in_str
        elif not in_str:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
                if depth == 0:
                    end = i
                    break
        i += 1
    if end is None:
        return None
    arg_str = f[start:end]

    # Split args on top-level commas
    args: list[str] = []
    depth = 0
    buf: list[str] = []
    in_str = False
    for ch in arg_str:
        if ch == '"':
            in_str = not in_str
            buf.append(ch)
            continue
        if not in_str:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            elif ch == "," and depth == 0:
                args.append("".join(buf).strip())
                buf = []
                continue
        buf.append(ch)
    args.append("".join(buf).strip())

    def unquote(a: str) -> str:
        a = a.strip()
        if len(a) >= 2 and a.startswith('"') and a.endswith('"'):
            return a[1:-1]
        return a

    args = [unquote(a) for a in args]
    return {
        "identifier": args[0] if len(args) > 0 else None,
        "mnemonic":   args[1] if len(args) > 1 else None,
        "period":     args[2] if len(args) > 2 and args[2] != "" else None,
        "ccy_scope":  args[3] if len(args) > 3 and args[3] != "" else None,
        "rank":       _safe_int(args[8]) if len(args) > 8 and args[8] != "" else None,
    }


def _safe_int(s: str) -> int | None:
    try:
        return int(s)
    except (ValueError, TypeError):
        return None


# ── Period → bucket router ────────────────────────────────────────────────
#
# Only one source of truth for how a (formula's) period token maps to
# `current`, `annual[N]`, or `quarterly[N]`. Accepts every variant we've
# seen: "IQ_FY-0", "FY-0", "IQ_FQ-3", "FQ-3", "IQ_FY", "FY", "IQ_FQ",
# "FQ", "IQ_LTM", "LTM", "", None.

_FY_N_RE = re.compile(r"FY[-_ ]?(-?\d+)$", re.IGNORECASE)  # "IQ_FY-0", "FY-0"
_FQ_N_RE = re.compile(r"FQ[-_ ]?(-?\d+)$", re.IGNORECASE)  # "IQ_FQ-3", "FQ-3"


def route_period(period) -> tuple[str, int | None]:
    """Return ('current' | 'annual' | 'quarterly', offset_or_None)."""
    if period is None or str(period).strip() == "":
        return ("current", None)
    s = str(period).strip()
    m = _FQ_N_RE.search(s)
    if m:
        return ("quarterly", int(m.group(1)))
    m = _FY_N_RE.search(s)
    if m:
        return ("annual", int(m.group(1)))
    # Bare period tokens (no offset) → current. Damodaran / CIQ treats the
    # latest period as the reference anchor when the 3rd arg is "IQ_FY" /
    # "IQ_FQ" / "LTM" without a suffix.
    if s.upper() in {"IQ_FY", "FY", "IQ_FQ", "FQ", "LTM", "IQ_LTM", "CURRENT"}:
        return ("current", None)
    return ("unknown", None)


# ── Main entry ────────────────────────────────────────────────────────────


def read_ciq_template(file_path: str | Path) -> dict:
    """Read a resolved CIQ template and return structured data.

    Uses a formula-first router: for each data row we parse the actual
    CIQ() call in column C (or A/B for geo-segment variants) and route
    by its period argument. The row-map is used for (row, variable-name)
    but its period field is ignored in favor of the parsed form.
    """
    path = str(file_path)

    # Load the workbook twice — once with formulas, once with cached values.
    # Column D holds `=C{row}`, which in data_only=True evaluates to the
    # cached CIQ result. Column C holds the CIQ formula itself, which in
    # data_only=False is the string we parse.
    wb_f = openpyxl.load_workbook(path, data_only=False)
    wb_v = openpyxl.load_workbook(path, data_only=True)
    ws_f = wb_f["CIQ_Data"]
    ws_v = wb_v["CIQ_Data"]

    # Ticker from B1 (same in both)
    ticker = str(ws_v["B1"].value or "").strip()

    # Build (row → variable_name) index from _RowMap if present. If not,
    # column A of the data sheet often holds the variable name for rows
    # our generator wrote (label column).
    row_to_variable: dict[int, str] = {}
    if "_RowMap" in wb_v.sheetnames:
        ws_map = wb_v["_RowMap"]
        for r in range(2, ws_map.max_row + 1):
            row_num = ws_map.cell(r, 1).value
            variable = ws_map.cell(r, 2).value
            if row_num and variable:
                row_to_variable[int(row_num)] = str(variable).strip()

    annual: dict[int, dict] = {}
    quarterly: dict[int, dict] = {}
    current: dict = {}
    period_dates: dict = {}

    _EXPENSE_FIELDS = {"interest_expense", "capex", "d_a", "operating_lease_expense"}
    _GEO_RAW: dict[str, float | str | None] = {}

    unknown_rows: list[tuple[int, str, str]] = []  # diagnostic accumulator

    # Walk every row the generator emitted (via _RowMap), or fall back to
    # scanning every row whose column A contains a non-empty variable name.
    target_rows: list[tuple[int, str]] = []
    if row_to_variable:
        target_rows = sorted(row_to_variable.items())
    else:
        for r in range(1, ws_v.max_row + 1):
            a = ws_v.cell(r, 1).value
            if isinstance(a, str) and a.strip():
                target_rows.append((r, a.strip()))

    for row, variable in target_rows:
        # Prefer the value from column D (which is =C{row} — the resolved
        # CIQ result). Fall back to column C if D is empty for some reason
        # (e.g. some hand-edited files skip the D mirror).
        resolved = ws_v.cell(row, 4).value
        if resolved is None:
            resolved = ws_v.cell(row, 3).value
        value = _parse_value(resolved)

        # Normalize expense-type fields: CIQ returns negatives, Damodaran
        # uses positives. Applied before routing.
        if variable in _EXPENSE_FIELDS and isinstance(value, (int, float)):
            value = abs(value)

        # Geographic segments route to their own bucket regardless of period.
        if variable.startswith("geo_seg_"):
            _GEO_RAW[variable] = value
            continue

        # Period dates: same special handling as before, but still derive
        # the FY offset from the parsed formula when possible for safety.
        formula = ws_f.cell(row, 3).value
        parsed = parse_ciq_formula(formula)
        parsed_period = parsed.get("period") if parsed else None

        if variable.startswith("period_date_"):
            formatted = _format_date(resolved)
            bucket, offset = route_period(parsed_period)
            if bucket == "annual":
                period_dates[f"period_date_annual_fy{abs(offset)}"] = formatted
                if offset == 0:
                    period_dates["period_date_annual"] = formatted
            elif bucket == "quarterly":
                period_dates["period_date_quarterly"] = formatted
            else:
                period_dates[variable] = formatted
            continue

        # Route by the parsed formula's period argument. If formula parse
        # failed (e.g. the user hand-pasted a value into column C), fall
        # back to current[] — never drop the value silently.
        bucket, offset = route_period(parsed_period)

        if bucket == "current":
            current[variable] = value
        elif bucket == "quarterly":
            quarterly.setdefault(offset, {})[variable] = value
        elif bucket == "annual":
            annual.setdefault(offset, {})[variable] = value
        else:
            # Formula unparseable OR period token is something we don't
            # recognize. Stash in current[] as a best-effort fallback and
            # log loudly so this shows up on the next dev session.
            unknown_rows.append((row, variable, str(parsed_period)))
            current[variable] = value

    wb_f.close()
    wb_v.close()

    if unknown_rows:
        logger.warning(
            "read_ciq_template: %d row(s) had unrecognized period tokens; "
            "stashed into current[] as fallback. sample: %s",
            len(unknown_rows), unknown_rows[:5],
        )

    # R&D fallback: if r_and_d_expense is zero/null, use r_and_d_expense_fn
    for dataset in [annual, quarterly]:
        for offset, data in dataset.items():
            primary = data.get("r_and_d_expense")
            fallback = data.get("r_and_d_expense_fn")
            if (primary is None or primary == 0) and fallback and fallback != 0:
                data["r_and_d_expense"] = fallback
            data.pop("r_and_d_expense_fn", None)

    # Also apply to current[] — some templates fetch R&D as current-period only.
    if current.get("r_and_d_expense") in (None, 0) and current.get("r_and_d_expense_fn"):
        current["r_and_d_expense"] = current["r_and_d_expense_fn"]
    current.pop("r_and_d_expense_fn", None)

    # ── Geographic segments post-processing ───────────────────────────────
    _JUNK_LABELS = (
        "headquarters", "corporate", "unallocated", "eliminations",
        "inter-segment", "intersegment", "restructuring", "finance income",
        "finance costs", "finance expense", "hq",
    )
    geo_segments: list[dict] = []

    if _GEO_RAW:
        # Primary path — geo_seg_{name|rev}_{rank} variables from our generator
        for rank in range(1, 11):
            name = _GEO_RAW.get(f"geo_seg_name_{rank}")
            rev = _GEO_RAW.get(f"geo_seg_rev_{rank}")
            if not isinstance(name, str) or not name.strip():
                continue
            if not isinstance(rev, (int, float)) or rev <= 0:
                continue
            if any(j in name.lower() for j in _JUNK_LABELS):
                continue
            geo_segments.append({"rank": rank, "name": name.strip(), "revenue": float(rev)})
    else:
        # Fallback — scan the sheet for IQ_GEO_SEG_*_ABS formulas in any
        # column. User may have hand-added them without touching _RowMap.
        wb_scan = openpyxl.load_workbook(path, data_only=False)
        ws_scan = wb_scan["CIQ_Data"]
        scanned: dict[int, dict] = {}
        for r in range(1, ws_scan.max_row + 1):
            for col in (1, 2, 3):  # A, B, C
                formula = ws_scan.cell(r, col).value
                if not isinstance(formula, str) or not formula.startswith("="):
                    continue
                up = formula.upper()
                is_name = "IQ_GEO_SEG_NAME_ABS" in up
                is_rev = "IQ_GEO_SEG_REV_ABS" in up
                if not (is_name or is_rev):
                    continue
                parsed = parse_ciq_formula(formula)
                rank = parsed.get("rank") if parsed else None
                if rank is None:
                    continue
                resolved = ws_v.cell(r, col).value   # data_only=True view
                if rank not in scanned:
                    scanned[rank] = {}
                if is_name and isinstance(resolved, str):
                    scanned[rank]["name"] = resolved
                elif is_rev and isinstance(resolved, (int, float)):
                    scanned[rank]["revenue"] = resolved
        wb_scan.close()
        for rank in sorted(scanned.keys()):
            row = scanned[rank]
            name = row.get("name"); rev = row.get("revenue")
            if not isinstance(name, str) or not name.strip():
                continue
            if not isinstance(rev, (int, float)) or rev <= 0:
                continue
            if any(j in name.lower() for j in _JUNK_LABELS):
                continue
            geo_segments.append({"rank": rank, "name": name.strip(), "revenue": float(rev)})

    if geo_segments:
        total_rev = sum(s["revenue"] for s in geo_segments)
        if total_rev > 0:
            for s in geo_segments:
                s["pct"] = s["revenue"] / total_rev

    return {
        "ticker": ticker,
        "annual": annual,
        "quarterly": quarterly,
        "current": current,
        "period_dates": period_dates,
        "geo_segments": geo_segments,
    }


# ── Helpers ───────────────────────────────────────────────────────────────


def _format_date(raw) -> str | None:
    """Convert Excel cell value (datetime, serial number, or string) to
    'Jan 31, 2026' format."""
    if raw is None:
        return None
    if isinstance(raw, datetime):
        return raw.strftime("%b %d, %Y")
    if isinstance(raw, (int, float)):
        n = float(raw)
        if 30000 < n < 60000:
            excel_epoch = datetime(1899, 12, 30)
            d = excel_epoch + timedelta(days=int(round(n)))
            return d.strftime("%b %d, %Y")
    s = str(raw).strip()
    if not s:
        return None
    try:
        n = float(s)
        if 30000 < n < 60000:
            excel_epoch = datetime(1899, 12, 30)
            d = excel_epoch + timedelta(days=int(round(n)))
            return d.strftime("%b %d, %Y")
    except ValueError:
        pass
    # Try dateutil-free parsers for common formats.
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%b-%Y", "%b %d, %Y"):
        try:
            return datetime.strptime(s, fmt).strftime("%b %d, %Y")
        except ValueError:
            pass
    return s


def _parse_value(raw):
    """Parse a resolved cell value into float / string / None.

    Handles CIQ #N/A / #REF! / getting-data sentinels."""
    if raw is None:
        return None
    if isinstance(raw, (int, float)):
        return float(raw)
    s = str(raw).strip()
    if not s:
        return None
    up = s.upper()
    if up in ("N/A", "#N/A", "NA", "#VALUE!", "#REF!", "#NAME?", "#DIV/0!"):
        return None
    if "GETTING" in up or "LOADING" in up or "#BUSY" in up:
        return None
    try:
        return float(s.replace(",", ""))
    except ValueError:
        return s
